### ISSUE TITLE
Cannot get the example in README to work

### ISSUE THREAD

**Issue by teu5us** [40ants/cl-telegram-bot#4]
I tried to create a basic bot, but keep getting this error:

```
debugger invoked on a TYPE-ERROR in thread
#<THREAD "telegram-bot" RUNNING {10048A2DA3}>:
  The value
    T
  is not of type
    STREAM
```

This seems to be caused by `get-updates` calling `make-request` with `:streamp t`. When I redefine `get-updates` to call `make-request` with `:streamp nil`, the bot starts working, but I'm not sure that this is the right way to go about the problem

**Comment by svetlyak40wt** [comment]
Please, show the full code to reproduce the problem.

**Comment by teu5us** [comment]
The code:

**Comment by svetlyak40wt** [comment]
I've checked the code. Seems `dexador` changed the way how it processes `:stream` option. I've removed it from the call.

Fix already available in Ultralisp. Update the dist please.

**Comment by teu5us** [comment]
Reinstalled with ql2nix, seems working now, thank you

**Comment by svetlyak40wt** [comment]
Cool! BTW, I never heard about ql2nix.

**Comment by teu5us** [comment]
It's just that NixOS has issues with Common Lisp and one can't use quicklisp, qlot or roswell as usual. So ql2nix uses quicklisp to generate package definitions for the nix package manager and then a development environment with all required dependencies can be created with nix-shell. [Here's](https://github.com/teu5us/ql2nix-project) an example
